Osx template
OpenVic2Project/OpenVic2 pull request #3
Opened 2023-01-30 14:25 UTC by KaiserOfNone

What it says on the tin.

2023-02-23 15:47 UTC, Spartan322 requested changes

2023-02-26 01:25 UTC, BrickPi commented on game/export_presets.cfg
> +export_path="export/osx/OpenVic2.dmg"
Not necessarily, OSX is interchangeable with macOS and shorter, if anything clearer and just as consistent, coming from a mac user & developer.

2023-02-26 03:52 UTC, Spartan322 commented on game/export_presets.cfg
> +export_path="export/osx/OpenVic2.dmg"
Well the standard right now is already present in the export directory, and its full descriptive.

2023-02-27 15:07 UTC, Spartan322 commented
One thing I suggest we do here is fix the clang mac compile issue before merge.

2023-02-27 15:48 UTC, Spartan322 commented
The compile issue seems to be caused by the use of `size_t` in Simulation.hpp, as `size_t` evaluates to an `unsigned long` however in godot-cpp, the exposed type relies upon `uint64_t` which if `__WORDSIZE` is 64 is the case, however if `__WORDSIZE` evaluates to 32, then `uint64_t` becomes `unsigned long long` instead.

2023-02-27 15:56 UTC, Spartan322 commented
Oops, wrongfully closed.

2023-02-27 15:57 UTC, merged