In game date
OpenVic2Project/OpenVic2 pull request #73
Opened 2023-03-23 21:37 UTC by markomitos

2023-03-24 20:00 UTC, ClarkeCode requested changes
Very good work!
Only a few small changes are needed (I've added suggestions)

Once those are applied and we remove the `.vs` folder, it should be good to merge 👍

2023-03-24 20:00 UTC, ClarkeCode commented on extension/src/Simulation.cpp
> +}
Moving to .cpp to avoid linker errors
```suggestion
}

OpenVic2::Simulation* OpenVic2::Simulation::_simulation = nullptr;

```

2023-03-25 11:33 UTC, Hop311 commented
I came up with some small fixes and extension ideas for Date, I'm planning on implementing them  + Zinc's suggestions.

# Fixes
- Remove `extension/src/.vs` (by running `git rm --cached -r  extension/src/.vs` from the repo's root directory) and add this to gitignore:
```
# Visual Studio
.vs/
```
- Use real days per month (but no leap years). Just put these in an array and use the `[month-1]` element as the day's maximum (remember to clamp the month first!)
```
31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31
```
- Move validation/clamping from the constructor to `setDate` (or it's own function, maybe `clampDate`?) and use `setDate` (or `clampDate`) in the constructor
    - could use `std::clamp`, at least for days and months

# Ideas
- Data types - maybe use `uint8_t` for day and month parts and `uint16_t` for the year? (might not be worth it but I'm p sure `uint64_t` isn't necessary)
    - numbers of days outside of a Date (e.g. number of days between `1-Jan-0` and `1-Jan-1836`, which is `670140`) needs to be `uint32_t` (or `int32_t`, since some subtracting Dates should be able to produce negative numbers of days) 
- Negative years (i.e. BC) - would be cool to support but not worth the effort right now
- Convert dates to/from total number of days since year `1-Jan-0`? An easy continuation would be days between dates (i.e. subtraction)
- Convert to/from string (pdxscript format `YYYY.MM.DD`). Maybe also support month names, at least as a Date-to-string option (victoria's UI uses `MONTH DD, YYYY`, e.g. `July 25, 1837`)?
- Operator overloads?
    - `Date + int32_t` - add a number of days to a date, stopping at `1-Jan-0` if int32_t is negative
    - `Date - int32_t = Date + (-int32_t)` 
    - `Date + Date` - add dates as number of days and convert back to Date (could add months directly, but then do you add days before or after months? Could change the maximum)
    - `Date - Date` - find number of days between two dates (could convert to a Date but would always return `1-Jan-0` for `Date1 < Date2`)
    - `Date < Date`, `Date <= Date`, `Date >= Date`, `Date > Date` - order Dates chronologically, easy to implement using `Date - Date = int32_t`
- Function to add `int32_t x` years, i.e. `365 * x` days
- Function to add `int32_t x` months? full months or convert to days using average? `average = 365/12 = 30.4`, could round and just do `31 * x` or use floats (or **fixed points** rather) and round after, so `365.0f/12.0f*static_cast<float>(x)` (I think casting is already done implicitly, but better to be explicit) rounded up, down, or to closest integer - benefit of this approach is that `12 months = 365 days`

2023-03-25 13:05 UTC, Spartan322 commented
> * `Date + Date` - add dates as number of days and convert back to Date (could add months directly, but then do you add days before or after months? Could change the maximum)
> * `Date - Date` - find number of days between two dates (could convert to a Date but would always return `1-Jan-0` for `Date1 < Date2`)
> * `Date < Date`, `Date <= Date`, `Date >= Date`, `Date > Date` - order Dates chronologically, easy to implement using `Date - Date = int32_t`

Might be helpful to be able to distinguish between a Date, an absolute period, and a TimeSpan, a relative period reference:

### TimeSpan

* TimeSpan only stores days as a single `int32_t`, (use `int64_t`?) this means it can represent a maximum amount of 2147483647 days, (both positive and negative) and thus a maximum amount of around 5883516 years.
* TimeSpan does not intrinsically store months or years.
* `TimeSpan.getAsMonths` method.
* `TimeSpan.getAsYears` method.
* `TimeSpan.getRemainingMonths` method, gets the amount of months remaining in its year, functionally a Date's month value.
* TimeSpan can be constructed with a static `TimeSpan.fromMonths(int32_t)` and `TimeSpan.fromYears(int32_t)`
* TimeSpan has a `toDate` method that converts the TimeSpan to its Date according to the TimeSpan's difference from `1-Jan-0`.
* `TimeSpan + TimeSpan = TimeSpan`, `TimeSpan - TimeSpan = TimeSpan`
* `TimeSpan * int32_t = TimeSpan`, the TimeSpan's days are multiplied by int32_t, thus the frames period is multiplied.
* `TimeSpan < TimeSpan`, `TimeSpan <= TimeSpan`, `TimeSpan >= TimeSpan`, `TimeSpan > TimeSpan`

### Date

* Date has a `toTimeSpan` method that converts the Date to a TimeSpan that's the relative difference from the `1-Jan-0`.
* `Date + Date` becomes impossible as adding together two absolute periods makes no semantic sense, should use `Date + TimeSpan = Date` instead.
* `Date + TimeSpan = Date`, to get the difference back you would then call `toTimeSpan` on the result.
* Might be useful to multiple TimeSpans? Months and years could be separately multiplied
* `Date - Date = TimeSpan`, the TimeSpan is the relative difference between the dates.
* `Date < Date`, `Date <= Date`, `Date >= Date`, `Date > Date` stays the same.
* Comparisons between TimeSpan and Date make no sense and thus aren't supported.
* `Date + int32_t`, `Date - int32_t = Date + (-int32_t)` are retained, but all cases of int32_t are in add and subtract are treated as TimeSpans for Date. TimeSpan will also support this overload as a result.

The biggest advantage to doing this is that Date can be made safer and we get to retain negative period references without the concept of negative Dates. Also enables performing backend implementations without exposing implementation details. For example we could theoretically perform lazy evaluation in a future implementation to increase performance so that TimeSpan never actually needs to calculate the Date's months and years itself and letting the Date technically calculate that. (this has the advantage of not changing the interface at all, which would be more difficult with Date)

2023-03-28 21:01 UTC, markomitos commented on extension/src/Simulation.hpp
> +		void setCurrentTime(std::chrono::time_point<std::chrono::high_resolution_clock> time);
these are supposed to be used when loading a save to set the proper date

2023-03-28 21:01 UTC, markomitos commented on extension/src/Simulation.cpp
> +
these are supposed to be used when loading a save to set the proper date

2023-04-13 22:38 UTC, Hop311 commented
Some suggestions:
- Add type aliases for day, month, year datatypes (maybe also for the days in timespan?)
- Reverse the order of arguments in Date's constructor and add default args, to match the `YYYY.MM.DD` written format and so things like `Date(1840)` make sense
```
Date(year_t year = 1836, month_t month = 1, day_t day = 1);
```
- Add a Date to std::string function in the format `YYYY.MM.DD`

2023-04-14 19:06 UTC, Spartan322 requested changes
This PR is being inconsistent between `using namespace OpenVic2` and the namespace OpenVic2 block btw, could were prefer the using case for C++ files?

2023-04-14 20:03 UTC, Spartan322 approved these changes

2023-04-14 20:04 UTC, ClarkeCode approved these changes

2023-04-14 20:16 UTC, merged